//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ScrollViewEventTriggerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ScrollViewEventTrigger), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetEventCall", SetEventCall);
		L.RegFunction("OnEventTrigger", OnEventTrigger);
		L.RegFunction("OnCallEvent", OnCallEvent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("OnClickCall", get_OnClickCall, set_OnClickCall);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEventCall(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ScrollViewEventTrigger obj = (ScrollViewEventTrigger)ToLua.CheckObject<ScrollViewEventTrigger>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.SetEventCall(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEventTrigger(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ScrollViewEventTrigger obj = (ScrollViewEventTrigger)ToLua.CheckObject<ScrollViewEventTrigger>(L, 1);
			obj.OnEventTrigger();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnCallEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ScrollViewEventTrigger obj = (ScrollViewEventTrigger)ToLua.CheckObject<ScrollViewEventTrigger>(L, 1);
			obj.OnCallEvent();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnClickCall(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ScrollViewEventTrigger obj = (ScrollViewEventTrigger)o;
			string ret = obj.OnClickCall;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnClickCall on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnClickCall(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ScrollViewEventTrigger obj = (ScrollViewEventTrigger)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnClickCall = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnClickCall on a nil value");
		}
	}
}

