//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ShapeSpineEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ShapeSpineEvent), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetLua_Call", SetLua_Call);
		L.RegFunction("SetLua_StartCall", SetLua_StartCall);
		L.RegFunction("SetLua_EndCall", SetLua_EndCall);
		L.RegFunction("GetCurAniTrack", GetCurAniTrack);
		L.RegFunction("SetSpineTimeScale", SetSpineTimeScale);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLua_Call(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ShapeSpineEvent obj = (ShapeSpineEvent)ToLua.CheckObject<ShapeSpineEvent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetLua_Call(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLua_StartCall(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ShapeSpineEvent obj = (ShapeSpineEvent)ToLua.CheckObject<ShapeSpineEvent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetLua_StartCall(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLua_EndCall(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ShapeSpineEvent obj = (ShapeSpineEvent)ToLua.CheckObject<ShapeSpineEvent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetLua_EndCall(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurAniTrack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ShapeSpineEvent obj = (ShapeSpineEvent)ToLua.CheckObject<ShapeSpineEvent>(L, 1);
			Spine.TrackEntry o = obj.GetCurAniTrack();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSpineTimeScale(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ShapeSpineEvent obj = (ShapeSpineEvent)ToLua.CheckObject<ShapeSpineEvent>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetSpineTimeScale(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

